name: "Deploy Codigo Facilito"

on:
  push:
    branches: ["master"]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
      steps:
        run: echo "pull of the code"
        run: echo "Run migrations"
        run: echo "Publish release with the new version"